### ISSUE TITLE
Locked door alert localization

### ISSUE THREAD

**Issue by dmizrahi** [manuelVo/foundryvtt-smart-doors#15]
Hello, Can you update the locked door alert to be localized? 

Thank you for your great module.

**Comment by manuelVo** [comment]
This is a surprisingly difficult request to fulfil. The alerts are regular chat messages and simply slapping a translation on the text like it's usually done for UI elements would lead to the interesting effect that the language used for the alerts would always be the one selected by the user that tried to open the door and that language would be displayed for anyone for that individual message. There might be a way to resolve this issue, but it requires further investigation.

**Comment by dmizrahi** [comment]
I Think for most of games, the players don't change the interface language set by the dm. You could just add a config to localize chatMessage only for the dm that want it.
