### ISSUE TITLE
Door icons stay if wall direction is not set to Both

### ISSUE THREAD

**Issue by Dillatr** [manuelVo/foundryvtt-smart-doors#16]
If the Wall Direction is set to Left or Right, door icons persist when changing the door status (open/closed, locked/unlocked). This occurs regardless is the door is secret or not.
![image](https://user-images.githubusercontent.com/91529833/149713211-c67d2337-2837-43a9-bf90-33cb66782158.png)

Wall Settings:
![image](https://user-images.githubusercontent.com/91529833/149713229-4764a977-3b00-4b85-bdf3-430e2789ce34.png)

**Comment by manuelVo** [comment]
This is a bug in the Foundryvtt core software. Please report it at the [Foundryvtt bug tracker](https://gitlab.com/foundrynet/foundryvtt/-/issues).
