### ISSUE TITLE
Weird conflict with Token Health Module

### ISSUE THREAD

**Issue by MrChessur** [manuelVo/foundryvtt-smart-doors#19]
I don't know exactly if this error affects other modules, but when this module and token health are enabled, neither can be updated in the module settings tab, such as with check boxes. It will just prompt a reload and the settings will remain what they were originally.

**Comment by manuelVo** [comment]
I cannot reproduce this. Which version of Token Health, Smart Doors and Foundry VTT are you using? Do you have any other modules than those two enabled?

**Comment by MrChessur** [comment]
Token Health Version is 0.5.5. 
Smart Doors Version is 1.3.2.
Foundry Version is 9.249(Version 9 Build 249).
Also I am running in the Pathfinder 2nd Edition version 3.3.1.10311(in case the conflict ties into this)

With only those two modules activated, If I go to module setting and try to change any of the check boxes on either module then save. It prompts a reload of the system, only on the GM side of it though. Then if I check the settings, they will have reverted to whatever the checkboxes were previously.

A work around for me and another GM was to disable one module, change the setting, then re-enable the other module and it will stick.

**Comment by MrChessur** [comment]
Tested on Dnd5e, same issue persists

**Comment by manuelVo** [comment]
From my point of view, this is a bug in Token Health. I've added details about this to the issue in their bug tracker. https://github.com/schlosrat/token-health/issues/69
