### ISSUE TITLE
Door Outlines cause high GPU load

### ISSUE THREAD

**Issue by rinnocenti** [manuelVo/foundryvtt-smart-doors#2]
I don't know why but when activating the option to activate the outlines of the doors, the module consumes about 20% more of the GPU, the frame rate drops about 10% on weaker machines.

**Comment by manuelVo** [comment]
The process of calculating the outlines more on the expensive side and the way it is now it is redone for each frame on each door. I didn't expect the calculation to be this expensive though. I'll see what I can do to improve the situation.

**Comment by manuelVo** [comment]
I've had an initial look at this and unfortunately it this seems to be a problem that is much harder to solve than I originally anticipated. I'll continue to think about how to improve the situation, but for the time being the only "soution" that I can offer is to disable the the outlines weaker machines.

**Comment by manuelVo** [comment]
I've had another look at this issue. Are you sure the slowdown is caused by high gpu load? I did some stress testing and on my machine the door outlines seemed to be more cpu limited than gpu limited. Unfortunately I don't have a slow machine that I could test this on.

**Comment by manuelVo** [comment]
Door icons have an outline by default in Foundry 0.8. This means this feature has run it's course when that foundry version becomes stable and will be removed from Smart Doors. As a result I won't be pursuing improving the performance of it anymore.
