### ISSUE TITLE
Secret Door status doesn't synchronize

### ISSUE THREAD

**Issue by ZanPhandelver** [manuelVo/foundryvtt-smart-doors#3]
Can Secret / Not Secret status synchronize in the same way that open/closed/locked does? Perhaps just as an option?

I'm using door groups along in conjunction with multilevel token teleporters to create a dungeon with rotating sections by teleporting the tokens around a large map with the rotating sections differently configured & want to have all the doors synced up, and being able to reveal all four versions of the secret doors with a single click would be helpful.

**Comment by manuelVo** [comment]
Synchronizing the secret door status isn't possible currently. However I like the idea of being able to do this and adding it to smart doors is certainly feasible.
