### ISSUE TITLE
Feature Request:  Incoprorate Design Doors

### ISSUE THREAD

**Issue by HippyCraig** [manuelVo/foundryvtt-smart-doors#31]
Looks like Designer Doors (https://github.com/Exitalterego/designerdoors) has been inactive for a while, maybe merging some of that into this would complement what your doing here.  Its a shame its been quite over on the other project as both of these tools work great together.

**Comment by esheyw** [comment]
Just posting a note for @HippyCraig that Designer Doors has updated for v11

**Comment by HippyCraig** [comment]
Great news
