### ISSUE TITLE
[Feature] Window Shutters, Closed Windows

### ISSUE THREAD

**Issue by Havoclivekiller** [manuelVo/foundryvtt-smart-doors#6]
The idea would be that you have a Movement restriction wall with full Perception but at the same time IsDoor. Just like a window shutter. A new icon, like this, would notify the players that there is a closed window in that spot. I don't have an idea about a "closed" window icon.
![window](https://user-images.githubusercontent.com/21118924/117702328-a4b78c00-b1c8-11eb-96f1-66e9927e3fd9.png)

**Comment by manuelVo** [comment]
I like the idea. However the Designer Doors module already allows to assign different icons to individual doors. That could already be used to achieve that functionality and I'm not very keen on duplicating it in smart doors, since the modules should work well together.

**Comment by Havoclivekiller** [comment]
Huh. Never saw this module in the release announcement channel. Thanks!
