### ISSUE TITLE
Clicking "Update Wall" in the Wall Configuration settings doesn't close the window

### ISSUE THREAD

**Issue by GambetTV** [manuelVo/foundryvtt-smart-doors#8]
Just a quality of life thing, not sure if this is a bug or intentional, but I find it really irritating that clicking Update Wall doesn't close the window, requiring an extra mouse click. If this is intended, maybe an extra option to disable this?

**Comment by manuelVo** [comment]
I can confirm that this is happening. The issue is actually more severe than described, because the door synchronization settings are no longer being saved as some foundry APIs around saving wall data appear to have changed.
